// ─── Comprehensive seed data for TechLand platform ───────────────────────────
// Used by the Admin panel "Initialize Data" button to seed roadmaps, modules,
// coding topics, and jobs into Supabase.

export const SEED_ROADMAPS = [
  {
    slug: "full-stack",
    domain_name: "Full Stack Development",
    title: "Full Stack Developer",
    description:
      "Master end-to-end web development from frontend to backend, databases, and deployment.",
    level: "Beginner" as const,
    estimated_duration: "6-9 months",
    icon: "🌐",
    sort_order: 1,
    modules: [
      {
        title: "HTML5 & Semantic Web",
        description: "Learn the building blocks of the web with modern HTML5 semantics.",
        youtube_url: "https://www.youtube.com/watch?v=pQN-pnXPaVg",
        instructor: "freeCodeCamp",
        duration: "4 hrs",
        sort_order: 1,
      },
      {
        title: "CSS3, Flexbox & Grid",
        description: "Style your pages with modern CSS including flexbox and grid layouts.",
        youtube_url: "https://www.youtube.com/watch?v=1Rs2ND1ryYc",
        instructor: "freeCodeCamp",
        duration: "5 hrs",
        sort_order: 2,
      },
      {
        title: "JavaScript ES6+",
        description: "Master modern JavaScript with ES6+ features, async/await, and more.",
        youtube_url: "https://www.youtube.com/watch?v=PkZNo7MFNFg",
        instructor: "freeCodeCamp",
        duration: "11 hrs",
        sort_order: 3,
      },
      {
        title: "Git & GitHub",
        description: "Version control your projects and collaborate with teams using Git.",
        youtube_url: "https://www.youtube.com/watch?v=RGOj5yH7evk",
        instructor: "freeCodeCamp",
        duration: "1 hr",
        sort_order: 4,
      },
      {
        title: "React.js Fundamentals",
        description:
          "Build dynamic UIs with React, hooks, state management and component patterns.",
        youtube_url: "https://www.youtube.com/watch?v=bMknfKXIFA8",
        instructor: "freeCodeCamp",
        duration: "12 hrs",
        sort_order: 5,
      },
      {
        title: "TypeScript",
        description: "Add static typing to your JavaScript for more robust, maintainable code.",
        youtube_url: "https://www.youtube.com/watch?v=d56mG7DezGs",
        instructor: "Fireship",
        duration: "1 hr",
        sort_order: 6,
      },
      {
        title: "Node.js & Express",
        description: "Build powerful REST APIs and server-side logic with Node.js.",
        youtube_url: "https://www.youtube.com/watch?v=Oe421EPjeBE",
        instructor: "freeCodeCamp",
        duration: "8 hrs",
        sort_order: 7,
      },
      {
        title: "PostgreSQL & SQL",
        description: "Master relational databases — queries, joins, indexing, and optimization.",
        youtube_url: "https://www.youtube.com/watch?v=qw--VYLpxG4",
        instructor: "freeCodeCamp",
        duration: "4 hrs",
        sort_order: 8,
      },
      {
        title: "REST APIs & Authentication",
        description: "Design secure APIs with JWT authentication, OAuth, and best practices.",
        youtube_url: "https://www.youtube.com/watch?v=7VLmLOiQ3ck",
        instructor: "Traversy Media",
        duration: "2 hrs",
        sort_order: 9,
      },
      {
        title: "Docker & CI/CD",
        description: "Containerize apps and set up automated deployment pipelines.",
        youtube_url: "https://www.youtube.com/watch?v=fqMOX6JJhGo",
        instructor: "freeCodeCamp",
        duration: "4 hrs",
        sort_order: 10,
      },
      {
        title: "AWS / Cloud Deployment",
        description: "Deploy your full-stack app to the cloud with AWS or Vercel.",
        youtube_url: "https://www.youtube.com/watch?v=3hLmDS179YE",
        instructor: "Traversy Media",
        duration: "2 hrs",
        sort_order: 11,
      },
      {
        title: "System Design Basics",
        description: "Understand scalability, caching, databases, and distributed systems.",
        youtube_url: "https://www.youtube.com/watch?v=lX4CrbXMsNQ",
        instructor: "Gaurav Sen",
        duration: "1 hr",
        sort_order: 12,
      },
    ],
  },
  {
    slug: "frontend",
    domain_name: "Frontend Development",
    title: "Frontend Developer",
    description: "Craft beautiful, performant, and accessible user interfaces for the modern web.",
    level: "Beginner" as const,
    estimated_duration: "4-6 months",
    icon: "🎨",
    sort_order: 2,
    modules: [
      {
        title: "HTML & Accessibility",
        description: "Build accessible websites following WCAG guidelines.",
        youtube_url: "https://www.youtube.com/watch?v=pQN-pnXPaVg",
        instructor: "freeCodeCamp",
        duration: "4 hrs",
        sort_order: 1,
      },
      {
        title: "Advanced CSS & Animations",
        description: "CSS variables, custom properties, transitions, and keyframe animations.",
        youtube_url: "https://www.youtube.com/watch?v=1Rs2ND1ryYc",
        instructor: "freeCodeCamp",
        duration: "5 hrs",
        sort_order: 2,
      },
      {
        title: "Responsive Web Design",
        description: "Build mobile-first, responsive layouts that work on all devices.",
        youtube_url: "https://www.youtube.com/watch?v=srvUrASNj0s",
        instructor: "freeCodeCamp",
        duration: "4 hrs",
        sort_order: 3,
      },
      {
        title: "JavaScript Deep Dive",
        description: "Closures, prototypes, the event loop, async patterns, and more.",
        youtube_url: "https://www.youtube.com/watch?v=PkZNo7MFNFg",
        instructor: "freeCodeCamp",
        duration: "11 hrs",
        sort_order: 4,
      },
      {
        title: "React Ecosystem",
        description: "React hooks, context, React Query, and component architecture.",
        youtube_url: "https://www.youtube.com/watch?v=bMknfKXIFA8",
        instructor: "freeCodeCamp",
        duration: "12 hrs",
        sort_order: 5,
      },
      {
        title: "State Management (Zustand/Redux)",
        description: "Manage complex application state with modern state management solutions.",
        youtube_url: "https://www.youtube.com/watch?v=5-1LM2NySR0",
        instructor: "Fireship",
        duration: "45 min",
        sort_order: 6,
      },
      {
        title: "Framer Motion & Animations",
        description: "Build stunning animations and page transitions with Framer Motion.",
        youtube_url: "https://www.youtube.com/watch?v=znbCa4Rr054",
        instructor: "Fireship",
        duration: "30 min",
        sort_order: 7,
      },
      {
        title: "Testing (Jest & Playwright)",
        description: "Write unit, integration, and e2e tests for your frontend applications.",
        youtube_url: "https://www.youtube.com/watch?v=7r4xVDI2vho",
        instructor: "freeCodeCamp",
        duration: "3 hrs",
        sort_order: 8,
      },
      {
        title: "Performance Optimization",
        description: "Core Web Vitals, lazy loading, code splitting, and bundle optimization.",
        youtube_url: "https://www.youtube.com/watch?v=AQDRaFRsi4I",
        instructor: "Google Chrome Developers",
        duration: "1 hr",
        sort_order: 9,
      },
    ],
  },
  {
    slug: "backend",
    domain_name: "Backend Development",
    title: "Backend Developer",
    description: "Build robust, scalable server-side systems, APIs, and microservices.",
    level: "Intermediate" as const,
    estimated_duration: "5-7 months",
    icon: "⚙️",
    sort_order: 3,
    modules: [
      {
        title: "Node.js & npm Ecosystem",
        description: "Master Node.js fundamentals, modules, streams, and the ecosystem.",
        youtube_url: "https://www.youtube.com/watch?v=Oe421EPjeBE",
        instructor: "freeCodeCamp",
        duration: "8 hrs",
        sort_order: 1,
      },
      {
        title: "Express.js REST APIs",
        description: "Build production-ready REST APIs with middleware, routing, and validation.",
        youtube_url: "https://www.youtube.com/watch?v=L72fhGm1tfE",
        instructor: "Traversy Media",
        duration: "2 hrs",
        sort_order: 2,
      },
      {
        title: "PostgreSQL & Knex/Prisma",
        description: "Relational databases with ORM, migrations, and query optimization.",
        youtube_url: "https://www.youtube.com/watch?v=qw--VYLpxG4",
        instructor: "freeCodeCamp",
        duration: "4 hrs",
        sort_order: 3,
      },
      {
        title: "MongoDB & Mongoose",
        description: "Document databases — schema design, aggregations, and indexing.",
        youtube_url: "https://www.youtube.com/watch?v=-56x56UppqQ",
        instructor: "freeCodeCamp",
        duration: "7 hrs",
        sort_order: 4,
      },
      {
        title: "Redis Caching",
        description: "Speed up your apps with Redis for caching, sessions, and pub/sub.",
        youtube_url: "https://www.youtube.com/watch?v=jgpVdJB2sKQ",
        instructor: "Fireship",
        duration: "30 min",
        sort_order: 5,
      },
      {
        title: "Authentication & Security",
        description: "JWT, OAuth2, bcrypt, rate limiting, and OWASP security practices.",
        youtube_url: "https://www.youtube.com/watch?v=7VLmLOiQ3ck",
        instructor: "Traversy Media",
        duration: "2 hrs",
        sort_order: 6,
      },
      {
        title: "Microservices Architecture",
        description: "Design distributed systems with microservices, message queues, and APIs.",
        youtube_url: "https://www.youtube.com/watch?v=rv4LlmLmVWk",
        instructor: "Fireship",
        duration: "1 hr",
        sort_order: 7,
      },
      {
        title: "Message Queues (Kafka/RabbitMQ)",
        description: "Async communication between services with message brokers.",
        youtube_url: "https://www.youtube.com/watch?v=1vLMuWsfMcA",
        instructor: "Amigoscode",
        duration: "3 hrs",
        sort_order: 8,
      },
      {
        title: "System Design Advanced",
        description: "Design Twitter, Netflix, Uber-scale systems from scratch.",
        youtube_url: "https://www.youtube.com/watch?v=lX4CrbXMsNQ",
        instructor: "Gaurav Sen",
        duration: "1 hr",
        sort_order: 9,
      },
    ],
  },
  {
    slug: "ai-ml",
    domain_name: "Artificial Intelligence",
    title: "AI / ML Engineer",
    description: "Build and deploy intelligent machine learning systems that learn from data.",
    level: "Intermediate" as const,
    estimated_duration: "9-12 months",
    icon: "🤖",
    sort_order: 4,
    modules: [
      {
        title: "Python for Data Science",
        description: "NumPy, Pandas, Matplotlib — the foundational Python data stack.",
        youtube_url: "https://www.youtube.com/watch?v=LHBE6Q9XlzI",
        instructor: "freeCodeCamp",
        duration: "12 hrs",
        sort_order: 1,
      },
      {
        title: "Linear Algebra & Statistics",
        description: "The math behind machine learning — vectors, matrices, probability.",
        youtube_url: "https://www.youtube.com/watch?v=uZeDTwWcnuY",
        instructor: "3Blue1Brown",
        duration: "3 hrs",
        sort_order: 2,
      },
      {
        title: "Machine Learning with Scikit-learn",
        description: "Regression, classification, clustering, and model evaluation.",
        youtube_url: "https://www.youtube.com/watch?v=7eh4d6sabA0",
        instructor: "Sentdex",
        duration: "8 hrs",
        sort_order: 3,
      },
      {
        title: "Feature Engineering",
        description: "Transform raw data into features that improve model performance.",
        youtube_url: "https://www.youtube.com/watch?v=6WDFfaYtN6s",
        instructor: "Kaggle",
        duration: "2 hrs",
        sort_order: 4,
      },
      {
        title: "Deep Learning with PyTorch",
        description: "Neural networks, backpropagation, CNNs, and RNNs from scratch.",
        youtube_url: "https://www.youtube.com/watch?v=c36lUUr864M",
        instructor: "freeCodeCamp",
        duration: "10 hrs",
        sort_order: 5,
      },
      {
        title: "Natural Language Processing",
        description: "Text processing, transformers, BERT, and fine-tuning LLMs.",
        youtube_url: "https://www.youtube.com/watch?v=8rXD5-xhemo",
        instructor: "freeCodeCamp",
        duration: "6 hrs",
        sort_order: 6,
      },
      {
        title: "Computer Vision",
        description: "Image classification, object detection, and image segmentation.",
        youtube_url: "https://www.youtube.com/watch?v=cPmjQ9V6Dqk",
        instructor: "freeCodeCamp",
        duration: "6 hrs",
        sort_order: 7,
      },
      {
        title: "MLOps & Model Deployment",
        description: "Deploy ML models with FastAPI, Docker, and cloud platforms.",
        youtube_url: "https://www.youtube.com/watch?v=1gwmCEOjBPg",
        instructor: "Krish Naik",
        duration: "4 hrs",
        sort_order: 8,
      },
      {
        title: "LLMs & Prompt Engineering",
        description: "Work with GPT, Llama, and build LLM-powered applications.",
        youtube_url: "https://www.youtube.com/watch?v=dOxUroR57xs",
        instructor: "freeCodeCamp",
        duration: "4 hrs",
        sort_order: 9,
      },
    ],
  },
  {
    slug: "data-science",
    domain_name: "Data Science",
    title: "Data Scientist",
    description:
      "Extract insights from data using statistics, machine learning, and visualization.",
    level: "Intermediate" as const,
    estimated_duration: "8-12 months",
    icon: "📊",
    sort_order: 5,
    modules: [
      {
        title: "Python Basics",
        description: "Python syntax, data structures, and programming fundamentals.",
        youtube_url: "https://www.youtube.com/watch?v=rfscVS0vtbw",
        instructor: "freeCodeCamp",
        duration: "4 hrs",
        sort_order: 1,
      },
      {
        title: "SQL for Data Analysis",
        description: "Complex queries, window functions, CTEs, and data exploration with SQL.",
        youtube_url: "https://www.youtube.com/watch?v=qw--VYLpxG4",
        instructor: "freeCodeCamp",
        duration: "4 hrs",
        sort_order: 2,
      },
      {
        title: "Statistics & Probability",
        description: "Hypothesis testing, distributions, confidence intervals for data analysis.",
        youtube_url: "https://www.youtube.com/watch?v=xxpc-HPKN28",
        instructor: "StatQuest",
        duration: "3 hrs",
        sort_order: 3,
      },
      {
        title: "Pandas & Data Wrangling",
        description: "Clean, transform, and analyze datasets with Pandas.",
        youtube_url: "https://www.youtube.com/watch?v=vmEHCJofslg",
        instructor: "freeCodeCamp",
        duration: "5 hrs",
        sort_order: 4,
      },
      {
        title: "Data Visualization",
        description: "Matplotlib, Seaborn, Plotly — communicate data through charts.",
        youtube_url: "https://www.youtube.com/watch?v=UO98lJQ3QGI",
        instructor: "freeCodeCamp",
        duration: "4 hrs",
        sort_order: 5,
      },
      {
        title: "Machine Learning Foundations",
        description: "Scikit-learn, model selection, cross-validation, and metrics.",
        youtube_url: "https://www.youtube.com/watch?v=7eh4d6sabA0",
        instructor: "Sentdex",
        duration: "8 hrs",
        sort_order: 6,
      },
      {
        title: "Power BI / Tableau",
        description: "Build interactive business dashboards and reports.",
        youtube_url: "https://www.youtube.com/watch?v=ykvAWKML9Gk",
        instructor: "freeCodeCamp",
        duration: "3 hrs",
        sort_order: 7,
      },
      {
        title: "A/B Testing & Experimentation",
        description: "Design experiments, measure impact, and make data-driven decisions.",
        youtube_url: "https://www.youtube.com/watch?v=VXsRLH29aQw",
        instructor: "CXL",
        duration: "1 hr",
        sort_order: 8,
      },
    ],
  },
  {
    slug: "data-analyst",
    domain_name: "Data Analytics",
    title: "Data Analyst",
    description: "Turn raw data into business decisions with SQL, Excel, and visualization tools.",
    level: "Beginner" as const,
    estimated_duration: "4-6 months",
    icon: "📈",
    sort_order: 6,
    modules: [
      {
        title: "Excel for Data Analysis",
        description: "PivotTables, VLOOKUP, charts, and data validation in Excel.",
        youtube_url: "https://www.youtube.com/watch?v=Vl0H-qTclOg",
        instructor: "freeCodeCamp",
        duration: "4 hrs",
        sort_order: 1,
      },
      {
        title: "SQL Fundamentals",
        description: "SELECT, JOINs, GROUP BY, subqueries — everything to query databases.",
        youtube_url: "https://www.youtube.com/watch?v=qw--VYLpxG4",
        instructor: "freeCodeCamp",
        duration: "4 hrs",
        sort_order: 2,
      },
      {
        title: "Statistics for Analysts",
        description: "Mean, median, standard deviation, distributions, and basic inference.",
        youtube_url: "https://www.youtube.com/watch?v=xxpc-HPKN28",
        instructor: "StatQuest",
        duration: "2 hrs",
        sort_order: 3,
      },
      {
        title: "Python for Analysis (Pandas)",
        description: "Data cleaning, exploration, and manipulation with Python.",
        youtube_url: "https://www.youtube.com/watch?v=vmEHCJofslg",
        instructor: "freeCodeCamp",
        duration: "5 hrs",
        sort_order: 4,
      },
      {
        title: "Power BI Dashboard",
        description: "Build interactive dashboards that update automatically.",
        youtube_url: "https://www.youtube.com/watch?v=ykvAWKML9Gk",
        instructor: "freeCodeCamp",
        duration: "3 hrs",
        sort_order: 5,
      },
      {
        title: "Google Analytics & Data Studio",
        description: "Track website metrics and build reporting dashboards.",
        youtube_url: "https://www.youtube.com/watch?v=gBMBjKKsJBg",
        instructor: "Google",
        duration: "2 hrs",
        sort_order: 6,
      },
    ],
  },
  {
    slug: "cybersecurity",
    domain_name: "Cybersecurity",
    title: "Cybersecurity Engineer",
    description:
      "Defend systems from modern threats through ethical hacking, threat modeling, and security engineering.",
    level: "Intermediate" as const,
    estimated_duration: "6-9 months",
    icon: "🔐",
    sort_order: 7,
    modules: [
      {
        title: "Networking Fundamentals",
        description: "TCP/IP, DNS, HTTP/S, firewalls — how data moves across the internet.",
        youtube_url: "https://www.youtube.com/watch?v=qiQR5rTSshw",
        instructor: "freeCodeCamp",
        duration: "9 hrs",
        sort_order: 1,
      },
      {
        title: "Linux for Hackers",
        description: "Command line, file permissions, processes, and scripting in Linux.",
        youtube_url: "https://www.youtube.com/watch?v=yzMLdjTrG7A",
        instructor: "freeCodeCamp",
        duration: "6 hrs",
        sort_order: 2,
      },
      {
        title: "Cryptography Basics",
        description: "Symmetric/asymmetric encryption, hashing, TLS, and PKI.",
        youtube_url: "https://www.youtube.com/watch?v=AQDRaFRsi4I",
        instructor: "Computerphile",
        duration: "2 hrs",
        sort_order: 3,
      },
      {
        title: "Ethical Hacking Fundamentals",
        description: "Reconnaissance, scanning, exploitation with Metasploit and Kali Linux.",
        youtube_url: "https://www.youtube.com/watch?v=3Kq1MIfTWCE",
        instructor: "freeCodeCamp",
        duration: "15 hrs",
        sort_order: 4,
      },
      {
        title: "Web Application Pentesting",
        description: "OWASP Top 10, SQL injection, XSS, CSRF, and Burp Suite.",
        youtube_url: "https://www.youtube.com/watch?v=sW10TlZF62w",
        instructor: "freeCodeCamp",
        duration: "4 hrs",
        sort_order: 5,
      },
      {
        title: "Network Security & Forensics",
        description: "Wireshark, IDS/IPS, network forensics, and incident response.",
        youtube_url: "https://www.youtube.com/watch?v=Tt08KFRKNNo",
        instructor: "freeCodeCamp",
        duration: "3 hrs",
        sort_order: 6,
      },
      {
        title: "Cloud Security (AWS)",
        description: "IAM, VPC, security groups, GuardDuty, and cloud compliance.",
        youtube_url: "https://www.youtube.com/watch?v=9STZ7MxkNVg",
        instructor: "freeCodeCamp",
        duration: "3 hrs",
        sort_order: 7,
      },
      {
        title: "SOC Analyst & SIEM",
        description: "Security operations, SIEM tools, threat hunting, and alerting.",
        youtube_url: "https://www.youtube.com/watch?v=Dk-ZqQ-bby4",
        instructor: "Gerald Auger",
        duration: "2 hrs",
        sort_order: 8,
      },
    ],
  },
  {
    slug: "cloud",
    domain_name: "Cloud Computing",
    title: "Cloud Engineer",
    description:
      "Architect and operate resilient, scalable cloud infrastructure on AWS, GCP, or Azure.",
    level: "Intermediate" as const,
    estimated_duration: "5-7 months",
    icon: "☁️",
    sort_order: 8,
    modules: [
      {
        title: "Cloud Computing Fundamentals",
        description: "IaaS, PaaS, SaaS — understanding the cloud service models.",
        youtube_url: "https://www.youtube.com/watch?v=M988_fsOSWo",
        instructor: "freeCodeCamp",
        duration: "2 hrs",
        sort_order: 1,
      },
      {
        title: "AWS Core Services",
        description: "EC2, S3, RDS, Lambda, VPC — the foundational AWS services.",
        youtube_url: "https://www.youtube.com/watch?v=3hLmDS179YE",
        instructor: "freeCodeCamp",
        duration: "5 hrs",
        sort_order: 2,
      },
      {
        title: "Linux & Bash Scripting",
        description: "Essential Linux skills and shell scripting for cloud engineers.",
        youtube_url: "https://www.youtube.com/watch?v=yzMLdjTrG7A",
        instructor: "freeCodeCamp",
        duration: "6 hrs",
        sort_order: 3,
      },
      {
        title: "Infrastructure as Code (Terraform)",
        description: "Define, provision, and manage cloud infrastructure with code.",
        youtube_url: "https://www.youtube.com/watch?v=SLB_c_ayRMo",
        instructor: "freeCodeCamp",
        duration: "3 hrs",
        sort_order: 4,
      },
      {
        title: "Docker & Container Orchestration",
        description: "Containerize applications and manage them with Docker Compose.",
        youtube_url: "https://www.youtube.com/watch?v=fqMOX6JJhGo",
        instructor: "freeCodeCamp",
        duration: "4 hrs",
        sort_order: 5,
      },
      {
        title: "Kubernetes (K8s)",
        description: "Deploy, scale, and manage containerized applications at scale.",
        youtube_url: "https://www.youtube.com/watch?v=X48VuDVv0do",
        instructor: "TechWorld with Nana",
        duration: "4 hrs",
        sort_order: 6,
      },
      {
        title: "AWS Solutions Architect",
        description: "Design highly available, fault-tolerant, and scalable cloud architectures.",
        youtube_url: "https://www.youtube.com/watch?v=Ia-UEYYR44s",
        instructor: "freeCodeCamp",
        duration: "10 hrs",
        sort_order: 7,
      },
      {
        title: "Cloud Cost Optimization",
        description: "FinOps practices, rightsizing, reserved instances, and cost monitoring.",
        youtube_url: "https://www.youtube.com/watch?v=9STZ7MxkNVg",
        instructor: "AWS",
        duration: "1 hr",
        sort_order: 8,
      },
    ],
  },
  {
    slug: "devops",
    domain_name: "DevOps",
    title: "DevOps Engineer",
    description:
      "Bridge development and operations to ship software faster with automation and reliability.",
    level: "Intermediate" as const,
    estimated_duration: "5-7 months",
    icon: "🔄",
    sort_order: 9,
    modules: [
      {
        title: "Linux & Shell Scripting",
        description: "The foundation of DevOps — Linux commands, bash scripting, cron jobs.",
        youtube_url: "https://www.youtube.com/watch?v=yzMLdjTrG7A",
        instructor: "freeCodeCamp",
        duration: "6 hrs",
        sort_order: 1,
      },
      {
        title: "Git & Branching Strategies",
        description: "Git flow, feature branches, rebasing, and merge strategies for teams.",
        youtube_url: "https://www.youtube.com/watch?v=RGOj5yH7evk",
        instructor: "freeCodeCamp",
        duration: "1 hr",
        sort_order: 2,
      },
      {
        title: "Docker & Containerization",
        description: "Build, ship, and run containers — Dockerfile, volumes, and networking.",
        youtube_url: "https://www.youtube.com/watch?v=fqMOX6JJhGo",
        instructor: "freeCodeCamp",
        duration: "4 hrs",
        sort_order: 3,
      },
      {
        title: "GitHub Actions CI/CD",
        description: "Automate testing, building, and deployment with GitHub Actions.",
        youtube_url: "https://www.youtube.com/watch?v=R8_veQiYBjI",
        instructor: "TechWorld with Nana",
        duration: "2 hrs",
        sort_order: 4,
      },
      {
        title: "Jenkins Pipeline",
        description: "Build enterprise-grade CI/CD pipelines with Jenkins.",
        youtube_url: "https://www.youtube.com/watch?v=LFDrDnKPOTg",
        instructor: "freeCodeCamp",
        duration: "3 hrs",
        sort_order: 5,
      },
      {
        title: "Kubernetes (K8s)",
        description: "Container orchestration — pods, services, deployments, and Helm charts.",
        youtube_url: "https://www.youtube.com/watch?v=X48VuDVv0do",
        instructor: "TechWorld with Nana",
        duration: "4 hrs",
        sort_order: 6,
      },
      {
        title: "Prometheus & Grafana Monitoring",
        description: "Metrics collection, alerting, and visualization for production systems.",
        youtube_url: "https://www.youtube.com/watch?v=9TJx7QTrTyo",
        instructor: "TechWorld with Nana",
        duration: "2 hrs",
        sort_order: 7,
      },
      {
        title: "Terraform & Infrastructure as Code",
        description: "Provision cloud infrastructure reproducibly with Terraform.",
        youtube_url: "https://www.youtube.com/watch?v=SLB_c_ayRMo",
        instructor: "freeCodeCamp",
        duration: "3 hrs",
        sort_order: 8,
      },
    ],
  },
  {
    slug: "mobile",
    domain_name: "Mobile App Development",
    title: "Mobile App Developer",
    description:
      "Build cross-platform mobile apps that run on millions of iOS and Android devices.",
    level: "Intermediate" as const,
    estimated_duration: "5-7 months",
    icon: "📱",
    sort_order: 10,
    modules: [
      {
        title: "Dart Programming Language",
        description: "Learn Dart — the language behind Flutter with strong typing and OOP.",
        youtube_url: "https://www.youtube.com/watch?v=5xlVP04905w",
        instructor: "freeCodeCamp",
        duration: "5 hrs",
        sort_order: 1,
      },
      {
        title: "Flutter UI Fundamentals",
        description: "Widgets, layouts, navigation, and state management in Flutter.",
        youtube_url: "https://www.youtube.com/watch?v=VPvVD8t02U8",
        instructor: "freeCodeCamp",
        duration: "10 hrs",
        sort_order: 2,
      },
      {
        title: "State Management (Provider/Riverpod)",
        description: "Manage app state efficiently with Provider or Riverpod.",
        youtube_url: "https://www.youtube.com/watch?v=O7V9IVkFKLQ",
        instructor: "Johannes Milke",
        duration: "2 hrs",
        sort_order: 3,
      },
      {
        title: "Firebase Integration",
        description: "Auth, Firestore database, cloud functions, and push notifications.",
        youtube_url: "https://www.youtube.com/watch?v=sfA3NWDBPZ4",
        instructor: "freeCodeCamp",
        duration: "6 hrs",
        sort_order: 4,
      },
      {
        title: "React Native (Alternative Path)",
        description: "Build iOS and Android apps with React and JavaScript.",
        youtube_url: "https://www.youtube.com/watch?v=0-S5a0eXPoc",
        instructor: "freeCodeCamp",
        duration: "8 hrs",
        sort_order: 5,
      },
      {
        title: "Native APIs & Device Features",
        description: "Camera, GPS, sensors, local storage, and push notifications.",
        youtube_url: "https://www.youtube.com/watch?v=ysz5S6PUM-U",
        instructor: "Fireship",
        duration: "1 hr",
        sort_order: 6,
      },
      {
        title: "App Store Deployment",
        description: "Submit your app to the Google Play Store and Apple App Store.",
        youtube_url: "https://www.youtube.com/watch?v=JHJCQ3Wa1Qg",
        instructor: "freeCodeCamp",
        duration: "1 hr",
        sort_order: 7,
      },
    ],
  },
  {
    slug: "ui-ux",
    domain_name: "UI/UX Design",
    title: "UI/UX Designer",
    description:
      "Design intuitive, beautiful interfaces that users love — from wireframes to high-fidelity prototypes.",
    level: "Beginner" as const,
    estimated_duration: "4-6 months",
    icon: "🎭",
    sort_order: 11,
    modules: [
      {
        title: "Design Principles & Theory",
        description: "Color theory, typography, spacing, and visual hierarchy fundamentals.",
        youtube_url: "https://www.youtube.com/watch?v=_Hp_dI0__qY",
        instructor: "Gary Simon",
        duration: "2 hrs",
        sort_order: 1,
      },
      {
        title: "Figma Masterclass",
        description: "Design, prototype, and collaborate in Figma — the industry standard.",
        youtube_url: "https://www.youtube.com/watch?v=FTFaQWZBqQ8",
        instructor: "Flux Academy",
        duration: "5 hrs",
        sort_order: 2,
      },
      {
        title: "UX Research Methods",
        description: "User interviews, usability testing, surveys, and persona creation.",
        youtube_url: "https://www.youtube.com/watch?v=Ovj4hFxko7c",
        instructor: "NNgroup",
        duration: "1 hr",
        sort_order: 3,
      },
      {
        title: "Wireframing & Information Architecture",
        description: "Structure apps logically and create low-fidelity wireframes.",
        youtube_url: "https://www.youtube.com/watch?v=KdfO_e0yK-g",
        instructor: "CareerFoundry",
        duration: "1 hr",
        sort_order: 4,
      },
      {
        title: "High-Fidelity Prototyping",
        description: "Create interactive prototypes with realistic interactions in Figma.",
        youtube_url: "https://www.youtube.com/watch?v=iBkXf6u8htI",
        instructor: "Figma",
        duration: "1 hr",
        sort_order: 5,
      },
      {
        title: "Design Systems",
        description: "Build scalable component libraries and design tokens.",
        youtube_url: "https://www.youtube.com/watch?v=EK-pHkc5EL4",
        instructor: "Figma",
        duration: "1 hr",
        sort_order: 6,
      },
      {
        title: "Portfolio Building",
        description: "Create a compelling UX portfolio that lands design jobs.",
        youtube_url: "https://www.youtube.com/watch?v=WKBVzBWAlVQ",
        instructor: "AJ&Smart",
        duration: "1 hr",
        sort_order: 7,
      },
    ],
  },
  {
    slug: "blockchain",
    domain_name: "Blockchain",
    title: "Blockchain Developer",
    description:
      "Build decentralized applications, smart contracts, and Web3 experiences on blockchain networks.",
    level: "Advanced" as const,
    estimated_duration: "6-9 months",
    icon: "⛓️",
    sort_order: 12,
    modules: [
      {
        title: "Blockchain Fundamentals",
        description:
          "How blockchains work — consensus, hashing, immutability, and decentralization.",
        youtube_url: "https://www.youtube.com/watch?v=bBC-nXj3Ng4",
        instructor: "3Blue1Brown",
        duration: "30 min",
        sort_order: 1,
      },
      {
        title: "Ethereum & Web3 Concepts",
        description: "Ethereum architecture, wallets, gas, EOA vs contracts.",
        youtube_url: "https://www.youtube.com/watch?v=coQ5dg8wM2o",
        instructor: "freeCodeCamp",
        duration: "5 hrs",
        sort_order: 2,
      },
      {
        title: "Solidity Smart Contracts",
        description: "Write, test, and deploy smart contracts on Ethereum.",
        youtube_url: "https://www.youtube.com/watch?v=M576WGiDBdQ",
        instructor: "freeCodeCamp",
        duration: "16 hrs",
        sort_order: 3,
      },
      {
        title: "Hardhat & Testing",
        description: "Development environment, unit tests, and scripts for Solidity projects.",
        youtube_url: "https://www.youtube.com/watch?v=9Wm1t2gmdsw",
        instructor: "Patrick Collins",
        duration: "4 hrs",
        sort_order: 4,
      },
      {
        title: "DeFi Protocols",
        description: "AMMs, lending protocols, yield farming — how DeFi works.",
        youtube_url: "https://www.youtube.com/watch?v=17QRFlml4pA",
        instructor: "Finematics",
        duration: "2 hrs",
        sort_order: 5,
      },
      {
        title: "Building a DApp with React",
        description: "Connect MetaMask, read/write contracts, and build a Web3 frontend.",
        youtube_url: "https://www.youtube.com/watch?v=coQ5dg8wM2o",
        instructor: "freeCodeCamp",
        duration: "5 hrs",
        sort_order: 6,
      },
    ],
  },
  {
    slug: "testing",
    domain_name: "Software Testing",
    title: "Software Test Engineer",
    description:
      "Ensure software quality with manual testing, automation frameworks, and CI/CD integration.",
    level: "Beginner" as const,
    estimated_duration: "4-6 months",
    icon: "🧪",
    sort_order: 13,
    modules: [
      {
        title: "Software Testing Fundamentals",
        description: "STLC, test types, bug lifecycle, and testing best practices.",
        youtube_url: "https://www.youtube.com/watch?v=sO8eGL6SFsA",
        instructor: "ISTQB Foundation",
        duration: "3 hrs",
        sort_order: 1,
      },
      {
        title: "Manual Testing",
        description: "Test case writing, exploratory testing, and defect reporting.",
        youtube_url: "https://www.youtube.com/watch?v=vLKKE5ZV0Fc",
        instructor: "freeCodeCamp",
        duration: "2 hrs",
        sort_order: 2,
      },
      {
        title: "Selenium with Java/Python",
        description: "Web UI automation with Selenium WebDriver — POM framework.",
        youtube_url: "https://www.youtube.com/watch?v=0VWMjU1fJEo",
        instructor: "freeCodeCamp",
        duration: "5 hrs",
        sort_order: 3,
      },
      {
        title: "API Testing with Postman",
        description: "Test REST APIs, create collections, and automate with Newman.",
        youtube_url: "https://www.youtube.com/watch?v=VywxIQ2ZXw4",
        instructor: "freeCodeCamp",
        duration: "2 hrs",
        sort_order: 4,
      },
      {
        title: "Playwright & Cypress",
        description: "Modern end-to-end testing frameworks for web applications.",
        youtube_url: "https://www.youtube.com/watch?v=7hr2_cBOej0",
        instructor: "freeCodeCamp",
        duration: "3 hrs",
        sort_order: 5,
      },
      {
        title: "Performance Testing (JMeter)",
        description: "Load testing, stress testing, and performance benchmarking.",
        youtube_url: "https://www.youtube.com/watch?v=M-gFpZnQjKM",
        instructor: "freeCodeCamp",
        duration: "2 hrs",
        sort_order: 6,
      },
      {
        title: "CI/CD Integration for QA",
        description: "Integrate automated tests into GitHub Actions and Jenkins pipelines.",
        youtube_url: "https://www.youtube.com/watch?v=R8_veQiYBjI",
        instructor: "TechWorld with Nana",
        duration: "2 hrs",
        sort_order: 7,
      },
    ],
  },
  {
    slug: "analytics",
    domain_name: "Analytics",
    title: "Business Analyst",
    description:
      "Bridge business and technology by analyzing requirements, modeling processes, and driving data-driven decisions.",
    level: "Beginner" as const,
    estimated_duration: "4-5 months",
    icon: "📋",
    sort_order: 14,
    modules: [
      {
        title: "Business Analysis Fundamentals",
        description: "BABOK framework, stakeholder management, and requirement elicitation.",
        youtube_url: "https://www.youtube.com/watch?v=7eh4d6sabA0",
        instructor: "Business Analyst Learnings",
        duration: "2 hrs",
        sort_order: 1,
      },
      {
        title: "Requirements Gathering",
        description: "User stories, use cases, acceptance criteria, and BDD.",
        youtube_url: "https://www.youtube.com/watch?v=0HMsh459h5c",
        instructor: "freeCodeCamp",
        duration: "1 hr",
        sort_order: 2,
      },
      {
        title: "Excel & Advanced Analytics",
        description: "Advanced Excel, Power Query, and analytics for business decisions.",
        youtube_url: "https://www.youtube.com/watch?v=Vl0H-qTclOg",
        instructor: "freeCodeCamp",
        duration: "4 hrs",
        sort_order: 3,
      },
      {
        title: "SQL for Business Analysts",
        description: "Query databases to extract business insights and build reports.",
        youtube_url: "https://www.youtube.com/watch?v=qw--VYLpxG4",
        instructor: "freeCodeCamp",
        duration: "4 hrs",
        sort_order: 4,
      },
      {
        title: "Process Modeling (BPMN)",
        description: "Model business processes with BPMN 2.0 notation.",
        youtube_url: "https://www.youtube.com/watch?v=BwkNceoybvA",
        instructor: "BPMN Training",
        duration: "1 hr",
        sort_order: 5,
      },
      {
        title: "Agile & Scrum for BAs",
        description: "Work in agile teams — sprint planning, backlog grooming, retrospectives.",
        youtube_url: "https://www.youtube.com/watch?v=2Vt7Ik8Ublw",
        instructor: "freeCodeCamp",
        duration: "1 hr",
        sort_order: 6,
      },
    ],
  },
];

export const SEED_CODING_TOPICS = [
  {
    name: "Arrays",
    difficulty: "Easy",
    sort_order: 1,
    leetcode_url: "https://leetcode.com/tag/array/",
    hackerrank_url:
      "https://www.hackerrank.com/domains/data-structures?filters%5Bsubdomains%5D%5B%5D=arrays",
    gfg_url: "https://www.geeksforgeeks.org/array-data-structure/",
    codechef_url: "https://www.codechef.com/practice/arrays",
  },
  {
    name: "Strings",
    difficulty: "Easy",
    sort_order: 2,
    leetcode_url: "https://leetcode.com/tag/string/",
    hackerrank_url:
      "https://www.hackerrank.com/domains/algorithms?filters%5Bsubdomains%5D%5B%5D=strings",
    gfg_url: "https://www.geeksforgeeks.org/string-data-structure/",
    codechef_url: "https://www.codechef.com/practice/strings",
  },
  {
    name: "Linked Lists",
    difficulty: "Easy",
    sort_order: 3,
    leetcode_url: "https://leetcode.com/tag/linked-list/",
    hackerrank_url:
      "https://www.hackerrank.com/domains/data-structures?filters%5Bsubdomains%5D%5B%5D=linked-lists",
    gfg_url: "https://www.geeksforgeeks.org/linked-list-data-structure/",
    codechef_url: null,
  },
  {
    name: "Stacks & Queues",
    difficulty: "Easy",
    sort_order: 4,
    leetcode_url: "https://leetcode.com/tag/stack/",
    hackerrank_url:
      "https://www.hackerrank.com/domains/data-structures?filters%5Bsubdomains%5D%5B%5D=stacks",
    gfg_url: "https://www.geeksforgeeks.org/stack-data-structure/",
    codechef_url: null,
  },
  {
    name: "Recursion",
    difficulty: "Medium",
    sort_order: 5,
    leetcode_url: "https://leetcode.com/tag/recursion/",
    hackerrank_url:
      "https://www.hackerrank.com/domains/algorithms?filters%5Bsubdomains%5D%5B%5D=recursion",
    gfg_url: "https://www.geeksforgeeks.org/recursion/",
    codechef_url: null,
  },
  {
    name: "Sorting Algorithms",
    difficulty: "Medium",
    sort_order: 6,
    leetcode_url: "https://leetcode.com/tag/sorting/",
    hackerrank_url:
      "https://www.hackerrank.com/domains/algorithms?filters%5Bsubdomains%5D%5B%5D=sorting",
    gfg_url: "https://www.geeksforgeeks.org/sorting-algorithms/",
    codechef_url: "https://www.codechef.com/practice/sorting",
  },
  {
    name: "Binary Search",
    difficulty: "Medium",
    sort_order: 7,
    leetcode_url: "https://leetcode.com/tag/binary-search/",
    hackerrank_url: null,
    gfg_url: "https://www.geeksforgeeks.org/binary-search/",
    codechef_url: null,
  },
  {
    name: "Trees",
    difficulty: "Medium",
    sort_order: 8,
    leetcode_url: "https://leetcode.com/tag/tree/",
    hackerrank_url:
      "https://www.hackerrank.com/domains/data-structures?filters%5Bsubdomains%5D%5B%5D=trees",
    gfg_url: "https://www.geeksforgeeks.org/binary-tree-data-structure/",
    codechef_url: null,
  },
  {
    name: "Graphs",
    difficulty: "Medium",
    sort_order: 9,
    leetcode_url: "https://leetcode.com/tag/graph/",
    hackerrank_url:
      "https://www.hackerrank.com/domains/algorithms?filters%5Bsubdomains%5D%5B%5D=graph-theory",
    gfg_url: "https://www.geeksforgeeks.org/graph-data-structure-and-algorithms/",
    codechef_url: null,
  },
  {
    name: "Hashing",
    difficulty: "Medium",
    sort_order: 10,
    leetcode_url: "https://leetcode.com/tag/hash-table/",
    hackerrank_url: null,
    gfg_url: "https://www.geeksforgeeks.org/hashing-data-structure/",
    codechef_url: null,
  },
  {
    name: "Dynamic Programming",
    difficulty: "Hard",
    sort_order: 11,
    leetcode_url: "https://leetcode.com/tag/dynamic-programming/",
    hackerrank_url: null,
    gfg_url: "https://www.geeksforgeeks.org/dynamic-programming/",
    codechef_url: "https://www.codechef.com/practice/dynamic-programming",
  },
  {
    name: "Greedy Algorithms",
    difficulty: "Hard",
    sort_order: 12,
    leetcode_url: "https://leetcode.com/tag/greedy/",
    hackerrank_url: null,
    gfg_url: "https://www.geeksforgeeks.org/greedy-algorithms/",
    codechef_url: null,
  },
  {
    name: "Backtracking",
    difficulty: "Hard",
    sort_order: 13,
    leetcode_url: "https://leetcode.com/tag/backtracking/",
    hackerrank_url: null,
    gfg_url: "https://www.geeksforgeeks.org/backtracking-algorithms/",
    codechef_url: null,
  },
  {
    name: "Heap / Priority Queue",
    difficulty: "Hard",
    sort_order: 14,
    leetcode_url: "https://leetcode.com/tag/heap-priority-queue/",
    hackerrank_url: null,
    gfg_url: "https://www.geeksforgeeks.org/heap-data-structure/",
    codechef_url: null,
  },
  {
    name: "Bit Manipulation",
    difficulty: "Hard",
    sort_order: 15,
    leetcode_url: "https://leetcode.com/tag/bit-manipulation/",
    hackerrank_url: null,
    gfg_url: "https://www.geeksforgeeks.org/bit-manipulation-101/",
    codechef_url: null,
  },
];

export const SEED_JOBS = [
  {
    role: "SDE Intern",
    company_name: "Google",
    location: "Bangalore",
    job_type: "Internship",
    application_link: "https://careers.google.com/students/",
    description: "Summer internship for CSE/IT students. Work on real Google products.",
    experience: "0-1 years",
  },
  {
    role: "Frontend Engineer",
    company_name: "Razorpay",
    location: "Remote",
    job_type: "Full-time",
    application_link: "https://razorpay.com/jobs/",
    description: "Build payment dashboards and developer tools with React and TypeScript.",
    experience: "0-2 years",
  },
  {
    role: "Data Analyst Intern",
    company_name: "Flipkart",
    location: "Bangalore",
    job_type: "Internship",
    application_link: "https://www.flipkartcareers.com/",
    description: "Analyze user behavior data and build dashboards for business teams.",
    experience: "0-1 years",
  },
  {
    role: "ML Engineer",
    company_name: "Sarvam AI",
    location: "Bangalore",
    job_type: "Full-time",
    application_link: "https://sarvam.ai/careers",
    description: "Build and deploy LLM-powered products for Indian language AI.",
    experience: "0-2 years",
  },
  {
    role: "Backend Developer",
    company_name: "Amazon",
    location: "Hyderabad",
    job_type: "Full-time",
    application_link: "https://www.amazon.jobs/en/teams/university-tech/",
    description: "SDE-1 role working on AWS services and Amazon retail platform.",
    experience: "Fresher",
  },
  {
    role: "Cybersecurity Analyst Intern",
    company_name: "Microsoft",
    location: "Bangalore",
    job_type: "Internship",
    application_link: "https://careers.microsoft.com/students/",
    description: "Security operations and threat analysis in Microsoft's security team.",
    experience: "0-1 years",
  },
  {
    role: "Full Stack Developer",
    company_name: "Zomato",
    location: "Gurugram",
    job_type: "Full-time",
    application_link: "https://www.zomato.com/careers",
    description: "Build features for 80M+ Zomato users using Node.js and React.",
    experience: "0-2 years",
  },
  {
    role: "DevOps Engineer",
    company_name: "Swiggy",
    location: "Bangalore",
    job_type: "Full-time",
    application_link: "https://careers.swiggy.com/",
    description: "Maintain CI/CD pipelines and Kubernetes clusters for real-time delivery systems.",
    experience: "0-2 years",
  },
  {
    role: "iOS Developer Intern",
    company_name: "Phonepe",
    location: "Bangalore",
    job_type: "Internship",
    application_link: "https://www.phonepe.com/careers/",
    description: "Build features for the PhonePe iOS app used by 500M+ users.",
    experience: "0-1 years",
  },
  {
    role: "Cloud Engineer",
    company_name: "Infosys",
    location: "Pune",
    job_type: "Full-time",
    application_link: "https://www.infosys.com/careers/",
    description: "AWS/Azure cloud migration and infrastructure management for enterprise clients.",
    experience: "Fresher",
  },
];
